'use client'

import { styleSheets } from '@cssfn/core'

import './StylesCSR'                    // client_side_rendering CSS (required)
import { StylesSSR } from './StylesSSR' // server_side_rendering CSS (optional)

import '@/theme.config'

import './layoutStyles.scss'

import { Header } from './Header'
import { Footer } from './Footer'

import { store } from '@/store/store'
import { Provider } from 'react-redux'

import { WEBSITE_LANGUAGE } from '@/website.config'



// styles:
styleSheets(
    () => import(/* webpackPrefetch: true */ './layoutStyles')
, { id: 'layout-eh4gver0nl' }); // a unique salt for SSR support, ensures the server-side & client-side have the same generated class names



export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}



export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang={WEBSITE_LANGUAGE}>
            <head>
                <StylesSSR />
            </head>
            <body>
                <Header />
                <Provider store={store}>
                    {children}
                </Provider>
                <Footer />
            </body>
        </html>
    )
}
