import './layoutStyles.scss'
import { LayoutStylesLoader } from './layoutStylesLoader'

import './StylesCSR'                    // client_side_rendering CSS (required)
import { StylesSSR } from './StylesSSR' // server_side_rendering CSS (optional)

import { Header } from './Header'
import { Footer } from './Footer'



export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}



export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <LayoutStylesLoader />
                <StylesSSR />
            </head>
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
