import './layoutStyles.scss'
import './layoutStylesLoader'
import { SsrStyles } from './SsrStyles'

import { Header } from './Header'
import { Footer } from './Footer'



export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}



export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <SsrStyles />
            </head>
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
